#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
FLAGS=()
CMDFILE=""

# if there's no command
if [ -z $1 ]
then
    CMDFILE="usage"
else
    CMDFILE="$1"
fi

for var in "$@"
do
    if [[ $var == -* ]]
    then
        FLAGS+=($var)
    fi
done

for FLAG in ${FLAGS[@]}; do
    case $FLAG in
      -H | --help | --usage | --version)
        CMDFILE="usage"
        ;;
      -D | --debug)
        DEBUG=true
        ;;
    esac
done

CMDPATH="$SCRIPT_DIR/commands/$CMDFILE"

if [ -e "$CMDPATH" ]; then
    source "$CMDPATH"
else
    echo "Command not found: $CMDFILE"
fi
