#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
CMDFILE=""

# if there's no command
if [ -z $1 ]
then
    CMDFILE="usage"
else
    CMDFILE="$1"
fi

CMDPATH="$SCRIPT_DIR/commands/$CMDFILE"

if [ -e "$CMDPATH" ]; then
    source "$CMDPATH"
else
    echo "Command not found: $CMDFILE"
fi
