#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
WORKDIR="$SCRIPT_DIR/../../../";

cd "$WORKDIR";

rm -rf ./build && npx tsc && cp config/application.toml build/config
