#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
FILE="$SCRIPT_DIR/../../../NECos.ts"

TS_NODE_INSTALLED=$(npx list -g ts-node)

echo $TS_NODE_INSTALLED

# npx ts-node "$FILE" -- $FLAGS