#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
FILE="$SCRIPT_DIR/../../../NECos.ts"

# check global ts node installation
TS_NODE_INSTALLED=$(npm list ts-node)

if [[ "$TS_NODE_INSTALLED" == *empty* ]]; then
    echo "ts-node is not installed. Please install ts-node to run NECos."
    return
fi

npx ts-node-esm "$FILE" -- $FLAGS
