#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
echo "NECos CLI Version" `cat "$SCRIPT_DIR/../VERSION"`
echo "NECos Repository Mainline Version" `git rev-parse ORIG_HEAD | cut -c1-8`
echo "NECos Local Repository Version" `git rev-parse HEAD | cut -c1-8`
echo ""
echo "Usage: ./necos [command] [OPTIONS]"
echo "Options:"
echo "  -h | --help | --usage     Shows the usage prompt"
echo "  -D | --debug              Enabled debugging mode"
echo ""
echo "Commands:"
echo "  usage                          Shows the NECos CLI usage information"
echo "  start                          Starts the NECos Application"
echo "  stop                           Gracefully stops any active NECos processes"
echo "  kill                           Forcefully stops any active NECos processes"
echo "  daemonize [--pm2 | --systemd ] Starts NECos via creating the specified method"
